resources:
- name: api
  type: git
  source: 
    uri: "git@github.com:dapi-co/api.git"
    branch: master
    private_key: ((priv-key))

- name: api-docker-image
  type: docker-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-registry))/services/api-service

jobs:
- name: build-docker-image
  plan:
  - get: api
    trigger: true
  - put: api-docker-image
    params: 
      build: api
    get_params:
      skip_download: true

- name: update-scale-set
  plan:
  - get: api-docker-image
    trigger: true
    passed:
    - build-docker-image
  - get: api
  - task: update-scale-set
    file: api/ci/tasks/update-scale-set.yml
    params:
      AZURE_TENANT: ((azure-tenant))
      AZURE_USER: ((azure-user))
      AZURE_PASS: ((azure-pass))
      AZURE_RG: ((azure-rg))
      AZURE_SS_NAME: Api0000SS
      SERVICE: api-service